background=#08090D
foreground=#D7D7D7

color0=#0A0A0F
color1=#FF5555
color2=#50FA7B
color3=#F1FA8C
color4=#6272A4
color5=#BD93F9
color6=#8BE9FD
color7=#F8F8F2

color8=#44475A
color9=#FF6E6E
color10=#69FF94
color11=#FFFFA5
color12=#8BE9FD
color13=#D6ACFF
color14=#A4FFFF
color15=#FFFFFF
