# DARK HOST Termux settings

# Hide Termux extra-key / shortcut row
extra-keys = []

# Do not automatically open the Android soft keyboard on startup
# Uncomment if desired:
# hide-soft-keyboard-on-startup = true
